### PR TITLE
Update social image

### PR DESCRIPTION
**Pull request by bouchenoiremarc**
Update social image according to https://github.com/framer/company/issues/16125.

### CODE REVIEW

**Comment by aron** [comment]
@bouchenoiremarc what am I supposed to be seeing? This PR looks like it just deletes the assets... Were you going to add new images?

**Comment by bouchenoiremarc** [comment]
bin

@aron GitHub seems to have a weird way of showing a changed image, this should be orange/yellow.

**Comment by aron** [comment]
Then I'm not seeing a difference? 
image

**Comment by bouchenoiremarc** [comment]
It's just for the social/meta/OG asset, and it's a tiny change: just adding the Framer logo to keep it consistent with the rest of the site.

change

**Comment by aron** [comment]
Just want to check the size change is intentional? 1200px x 630px -> 800px x 400px

**Comment by bouchenoiremarc** [comment]
I think so, but just to be sure, @monikamichalczyk?

**Comment by monikamichalczyk** [comment]
yup, all of our OG images are in 800x400

**Pull request merged**
