### PR TITLE
Add navigation docs under Beta flag

### PR DESCRIPTION
**Pull request by addisonschultz**
Adding in documentation for using Framer's Navigation API through code. Features currently still in Beta are marked as so.

### CODE REVIEW

**Comment by addisonschultz** [comment]
@jonastreub Let me know if you need anything else, but otherwise feel free to merge after updating the library 👍

**Comment by addisonschultz** [comment]
@hemlok Whenever the Beta flags are taken off of `useNavigation` and the like, this can be merged 👍

**Comment by hemlok** [comment]
Did that earlier today! You can run the make command to update 💪

**Comment by addisonschultz** [comment]
Just saw it now :) https://github.com/framer/FramerStudio/pull/5840

Awesome, will do!

**Pull request merged**
