### PR TITLE
Add useIsInCurrentNavigationTarget to Utilities

### PR DESCRIPTION
**Pull request by hemlok**

### CODE REVIEW

**Comment by hemlok** [comment]
Will rebase after the library update is merged ☝️

**Comment by hemlok** [comment]
@addisonschultz is this the right place for this? I initially wondered if it belonged in the Navigation section, but I think it is more broadly/generally useful than that.

**Comment by addisonschultz** [comment]
@hemlok Can you link the PR for the library change?

**Comment by hemlok** [comment]
https://github.com/framer/api-docs/pull/112

**Pull request merged**
